# <<<<<<< HEAD
# # Generated by Django 5.0.6 on 2024-08-07 03:29
# =======
# # Generated by Django 5.0.6 on 2024-08-07 03:07
# >>>>>>> b1cada59d1cf5d583ad86d61ec0b6423fcdf084e

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.state')),
            ],
        ),
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_insumo', models.CharField(max_length=100)),
                ('costo', models.FloatField()),
                ('unidades', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_user', models.CharField(blank=True, choices=[('Cliente', 'Cliente'), ('Vendedor', 'Vendedor'), ('Proveedor', 'Proveedor'), ('Mantenimiento', 'Mantenimiento')], default='Cliente', max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.municipality')),
            ],
        ),
        migrations.CreateModel(
            name='TypeWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_work', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('salary', models.FloatField(default=0.0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.user')),
            ],
        ),
        migrations.AddField(
            model_name='supplier',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.user'),
        ),
    ]
