# <<<<<<< HEAD
# # Generated by Django 5.0.6 on 2024-08-07 16:53
# =======
# # Generated by Django 5.0.6 on 2024-08-07 14:02
# >>>>>>> ab17e1dcee52760a07404b4ca6cc4717f6d4c436

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.municipality'),
        ),
    ]
