# Generated by Django 5.0.6 on 2024-08-07 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_code',
            field=models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='El código hexadecimal debe estar en el formato #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')]),
            preserve_default=False,
        ),
    ]
