# Generated by Django 5.0.6 on 2024-08-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshop',
            name='units',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
    ]
